### ISSUE TITLE
jsdoc not running properly to create docs

### ISSUE THREAD

**Issue by podfeet** [bartificer/xkpasswd-js#28]
Attemptin to run `npm run docs` results in an error about jsdoc not supporting BigInt:

```
npm run docs

> xkpasswdjs@0.1.0 docs
> docDir='./docs'; [[ -e "$docDir" ]] && rm -rf "$docDir/"*; npx jsdoc -c ./jsdoc.conf.json --destination "$docDir/" --template node_modules/docdash

/Users/allison/htdocs/xkpasswd-js/node_modules/jsdoc/lib/jsdoc/src/astnode.js:275
            str = JSON.stringify(tempObject);
                       ^

TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at exports.nodeToValue (/Users/allison/htdocs/xkpasswd-js/node_modules/jsdoc/lib/jsdoc/src/astnode.js:275:24)
    at exports.getInfo (/Users/allison/htdocs/xkpasswd-js/node_modules/jsdoc/lib/jsdoc/src/astnode.js:511:26)
    at makeSymbolFoundEvent (/Users/allison/htdocs/xkpasswd-js/node_modules/jsdoc/lib/jsdoc/src/visitor.js:477:33)
    at Visitor.visitNode (/Users/allison/htdocs/xkpasswd-js/node_modules/jsdoc/lib/jsdoc/src/visitor.js:834:19)
    at Visitor.visit (/Users/allison/htdocs/xkpasswd-js/node_modules/jsdoc/lib/jsdoc/src/visitor.js:756:21)
    at Walker.recurse (/Users/allison/htdocs/xkpasswd-js/node_modules/jsdoc/lib/jsdoc/src/walker.js:694:42)
    at Parser._walkAst (/Users/allison/htdocs/xkpasswd-js/node_modules/jsdoc/lib/jsdoc/src/parser.js:305:22)
    at Parser._parseSourceCode (/Users/allison/htdocs/xkpasswd-js/node_modules/jsdoc/lib/jsdoc/src/parser.js:296:22)
    at Parser.parse (/Users/allison/htdocs/xkpasswd-js/node_modules/jsdoc/lib/jsdoc/src/parser.js:202:22)
    at module.exports.cli.parseFiles (/Users/allison/htdocs/xkpasswd-js/node_modules/jsdoc/cli.js:365:46)
    at module.exports.cli.main (/Users/allison/htdocs/xkpasswd-js/node_modules/jsdoc/cli.js:234:18)
    at module.exports.cli.runCommand (/Users/allison/htdocs/xkpasswd-js/node_modules/jsdoc/cli.js:186:9)
    at /Users/allison/htdocs/xkpasswd-js/node_modules/jsdoc/jsdoc.js:93:9
    at Object.<anonymous> (/Users/allison/htdocs/xkpasswd-js/node_modules/jsdoc/jsdoc.js:94:3)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)

Node.js v18.18.0
```

**Comment by hepabolu** [comment]
#34 is a temporary fix for this issue
